#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/sxhkd/bspwm/sxhkdrc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
#~/.config/polybar/shades/launch.sh &
# ~/.config/polybar/shapes/launch.sh &
# ~/.config/polybar/material/launch.sh &
# ~/.config/polybar/grayblocks/launch.sh &
~/.config/polybar/blocks/launch.sh &
#nm-applet &
#cbatticon &
#diodon &
#blueman-applet &
nitrogen --restore &
picom --experimental-backends -b &
dunst &
